development:
  app_name: Php Default Client
  app_url: http://localhost:3002
  enable_mfa_url: /request_enable_mfa
  client_url: http://localhost/phpclient
  client_path: /home/amir/public_html/phpclient
  server_url: http://localhost:3002
  auth_url: /api/v8/authenticate
  mfa_check_url: /api/v8/check
  mfa_check_client_url: /mfa_check
  client_id: "0908aba0a8c84d870c0f3d2891b274d8f76213e40db30e9bad578729932583dd"
  client_secret: "1aff5053acb1f7f1babaab04c43aa668cbc1cec32e6b33eb0488d20b6a65016d"
  dsn: "mysql:dbname=phpclient;host=localhost"
  db_username: "root"
  db_password: "123456"
  
production:
  app_name: Php Default Client
  app_url: http://localhost:3002
  enable_mfa_url: /request_enable_mfa
  client_url: http://localhost/phpclient
  server_url: http://localhost:3002
  auth_url: /api/v8/authenticate
  mfa_check_url: /api/v8/check
  mfa_check_client_url: /mfa_check
  client_id: "0908aba0a8c84d870c0f3d2891b274d8f76213e40db30e9bad578729932583dd"
  client_secret: "1aff5053acb1f7f1babaab04c43aa668cbc1cec32e6b33eb0488d20b6a65016d"
  dsn: "mysql:dbname=phpclient;host=localhost"
  db_username: "root"
  db_password: "123456"